name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - #{{ inputs.debug }}

on: 
 push:
 workflow_dispatch:
   inputs:
     debug:
       type: boolean
       default: false
   

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "Event Name : ${{ github.event_name }} "
                echo "REf : ${{ github.ref }} "
                echo "SHA : ${{ github.sha }} "
                echo "Actor : ${{ github.actor }} "
                echo "Workflow: ${{ github.workflow }} "
                echo "Run Id : ${{ github.run_id }} "
                echo "Run number : ${{ github.run_number }} "
            - name:   Retreive Variable
              run: |
                echo "Variable value ${{ vars.MY_VAR}}"  


