name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on: 
 workflow_dispatch:
   inputs:
     debug:
       type: boolean
       default: false

env:
   MY_WORKFLOW_VAR: 'workflow'
   MY_OVERWRITTEN_VAR: 'workflow'
   

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
          MY_JOB_VAR: 'job'
          MY_OVERWRITTEN_VAR : 'job overritten'
        steps:
            - name: Display Information
              run: |
                echo "Event Name : ${{ github.event_name }} "
                echo "REf : ${{ github.ref }} "
                echo "SHA : ${{ github.sha }} "
                echo "Actor : ${{ github.actor }} "
                echo "Workflow: ${{ github.workflow }} "
                echo "Run Id : ${{ github.run_id }} "
                echo "Run number : ${{ github.run_number }} "
            - name:   Retreive Variable
              run: |
                echo "Variable value ${{ vars.MY_VAR }}"  
            - name: Print Env var 
              env:
                MY_OVERWRITTEN_VAR: 'step'
              run: |
                echo "Variable value $MY_OVERWRITTEN_VAR"  
                echo "Variable value $MY_WORKFLOW_VAR" 
                echo "Variable value $MY_JOB_VAR" 
            - name: Print Env var after step 
              run: echo "Variable value after step $MY_OVERWRITTEN_VAR"  
                



