name: 09 -  Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
    echo1:
     runs-on: ubuntu-latest
     steps: 
        - name: run PR title
          run: echo '${{ github.event.pull_request.tile }}'
        - name: Print PR labels
          run: |
            cat << EOF
            ${{ toJSON(github.event.pull_request.lables) }}
            EOF
        - name: Bug step
          if: ${{ !cancelled() && contains(github.event.pull_request.title , 'fix') }}
          run: echo 'I am bug fix'  
        - name: Sleep job 5 s
          run: sleep 5  
        - name: I will be skipped
          if: ${{ success() }}
          run: echo 'I will print if other steps succeed'
        - name: I will be execute
          if: ${{ failure() }}
          run: echo 'I will print if any step fails'
        - name: I will be execute always
          if: ${{ !cancelled() }}
          run: echo 'I will always print except when workflow is cancelled'
        - name: I will be execute when workflow cancelled
          if: ${{ cancelled() }}
          run: echo 'I will execute when workflow is cancelled'