name: 09 -  Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
    echo1:
     runs-on: ubuntu-latest
     steps: 
        - name: Failing step
          run: exit 1
        - name: I will be skipped
          if: ${{ success() }}
          run: echo 'I will print if other steps succeed'
        - name: I will be execute
          if: ${{ failure() }}
          run: echo 'I will print if any step fails'
        - name: I will be execute always
          if: ${{ !cancelled() }}
          run: echo 'I will always print except when workflow is cancelled'
        - name: I will be execute when workflow cancelled
          if: ${{ cancelled() }}
          run: echo 'I will execute when workflow is cancelled'