name: 17 - Custom - action - composite

on:
  workflow_dispatch:

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
        - uses: actions/checkout@v4
        - name: Setup node and npm dependencies
          uses: ./.github/actions/composite-cache-deps
          with: 
            node-version: 20.x
            working-dir: ${{ env.working-directory }}
        - name: Testing
          run: npm run test
        - name: Building
          run: npm run build